import SwiftUI

struct RelaySettingsView: View {
    @ObservedObject private var preferences = RelayPreferences.shared

    var body: some View {
        HStack(spacing: 0) {
            settings
                .frame(width: 350)
            Divider().overlay(RelayTheme.line.opacity(0.45))
            preview
                .frame(maxWidth: .infinity, maxHeight: .infinity)
        }
        .frame(width: 760, height: 500)
        .background(RelayTheme.canvas)
        .preferredColorScheme(.dark)
    }

    private var settings: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 22) {
                VStack(alignment: .leading, spacing: 5) {
                    Text("Settings")
                        .font(.system(size: 19, weight: .semibold))
                    Text("Terminal and workspace preferences")
                        .font(.system(size: 12))
                        .foregroundStyle(RelayTheme.textMuted)
                }

                settingSection("Terminal") {
                    TextField("Font family", text: $preferences.fontFamily)
                        .textFieldStyle(.plain)
                        .padding(.horizontal, 10)
                        .frame(height: 32)
                        .background(RelayTheme.elevated, in: RoundedRectangle(cornerRadius: 8, style: .continuous))
                    valueSlider("Size", value: $preferences.fontSize, range: 9...24, suffix: "pt")
                    valueSlider("Padding", value: $preferences.terminalPadding, range: 0...20, suffix: "px")
                    Toggle("Blink cursor", isOn: $preferences.cursorBlink)
                }

                settingSection("Workspace") {
                    Picker("Palette", selection: $preferences.palette) {
                        ForEach(RelayTerminalPalette.allCases) { palette in
                            Text(palette.label).tag(palette)
                        }
                    }
                    .pickerStyle(.segmented)
                    Toggle("Compact interface", isOn: $preferences.compactInterface)
                    Toggle("Hide navigator in full screen", isOn: $preferences.hideSidebarInFullScreen)
                }

                settingSection("Images") {
                    Toggle("Show images generated by agents", isOn: $preferences.showArtifactPreviews)
                    Picker("Presentation", selection: $preferences.artifactPresentation) {
                        ForEach(RelayArtifactPresentation.allCases) { presentation in
                            Text(presentation.label).tag(presentation)
                        }
                    }
                    .pickerStyle(.segmented)
                    .disabled(!preferences.showArtifactPreviews)
                    Text("Relay securely fetches image files referenced by Codex and Claude from the connected node.")
                        .font(.system(size: 10.5))
                        .foregroundStyle(RelayTheme.textMuted)
                        .fixedSize(horizontal: false, vertical: true)
                }
            }
            .padding(26)
        }
        .foregroundStyle(RelayTheme.text)
        .background(RelayTheme.sidebar)
    }

    private var preview: some View {
        VStack(alignment: .leading, spacing: 16) {
            Text("Preview")
                .font(.system(size: 12, weight: .medium))
                .foregroundStyle(RelayTheme.textMuted)
            VStack(spacing: 0) {
                HStack(spacing: 7) {
                    Circle().fill(RelayTheme.mint).frame(width: 6, height: 6)
                    Text("hpc-login  /  codex")
                        .font(.system(size: 10.5, weight: .medium))
                    Spacer()
                    Text("Connected")
                        .font(.system(size: 9, weight: .medium))
                        .foregroundStyle(RelayTheme.mint)
                }
                .padding(.horizontal, 12)
                .frame(height: 34)
                .background(RelayTheme.surface)

                VStack(alignment: .leading, spacing: 8) {
                    Text("$ codex")
                    Text("› build the next experiment")
                        .foregroundStyle(RelayTheme.textMuted)
                    Text("● Working on hpc-login")
                        .foregroundStyle(RelayTheme.mint)
                    Text("_")
                        .foregroundStyle(RelayTheme.blue)
                }
                .font(.custom(preferences.fontFamily.isEmpty ? "Menlo" : preferences.fontFamily, size: preferences.fontSize))
                .padding(preferences.terminalPadding)
                .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
                .background(Color(hex: UInt32(preferences.palette.background, radix: 16) ?? 0x0B1018))
            }
            .clipShape(RoundedRectangle(cornerRadius: 12, style: .continuous))
            .overlay { RoundedRectangle(cornerRadius: 12).stroke(RelayTheme.line.opacity(0.55)) }
        }
        .padding(26)
    }

    private func settingSection<Content: View>(_ title: String, @ViewBuilder content: () -> Content) -> some View {
        VStack(alignment: .leading, spacing: 9) {
            Text(title)
                .font(.system(size: 12, weight: .medium))
                .foregroundStyle(RelayTheme.textMuted)
            VStack(alignment: .leading, spacing: 12) {
                content()
            }
            .padding(12)
            .background(RelayTheme.surface, in: RoundedRectangle(cornerRadius: 12, style: .continuous))
        }
    }

    private func valueSlider(_ label: String, value: Binding<Double>, range: ClosedRange<Double>, suffix: String) -> some View {
        HStack(spacing: 10) {
            Text(label).font(.system(size: 11.5)).frame(width: 48, alignment: .leading)
            Slider(value: value, in: range, step: 0.5).tint(RelayTheme.blue)
            Text("\(value.wrappedValue, specifier: "%.1f") \(suffix)")
                .font(.system(size: 10, weight: .medium, design: .monospaced))
                .foregroundStyle(RelayTheme.textMuted)
                .frame(width: 57, alignment: .trailing)
        }
    }
}
