import SwiftUI

struct RelaySettingsView: View {
    @ObservedObject private var preferences = RelayPreferences.shared

    var body: some View {
        HStack(spacing: 0) {
            settings
                .frame(width: 360)
            Divider().overlay(RelayTheme.line)
            preview
                .frame(maxWidth: .infinity, maxHeight: .infinity)
        }
        .frame(width: 720, height: 470)
        .background(RelayTheme.canvas)
        .preferredColorScheme(.dark)
    }

    private var settings: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 25) {
                VStack(alignment: .leading, spacing: 5) {
                    Text("Relay Settings")
                        .font(.system(size: 20, weight: .bold, design: .rounded))
                    Text("Terminal rendering and workspace behavior")
                        .font(.system(size: 11.5))
                        .foregroundStyle(RelayTheme.textMuted)
                }

                settingSection("TYPE") {
                    TextField("Font family", text: $preferences.fontFamily)
                        .textFieldStyle(.plain)
                        .padding(.horizontal, 10)
                        .frame(height: 32)
                        .background(RelayTheme.surface, in: RoundedRectangle(cornerRadius: 7))
                    valueSlider("Size", value: $preferences.fontSize, range: 9...24, suffix: "pt")
                    valueSlider("Padding", value: $preferences.terminalPadding, range: 0...20, suffix: "px")
                }

                settingSection("APPEARANCE") {
                    Picker("Palette", selection: $preferences.palette) {
                        ForEach(RelayTerminalPalette.allCases) { palette in
                            Text(palette.label).tag(palette)
                        }
                    }
                    .pickerStyle(.segmented)
                    Toggle("Compact interface", isOn: $preferences.compactInterface)
                    Toggle("Hide navigator in full screen", isOn: $preferences.hideSidebarInFullScreen)
                }

                settingSection("ARTIFACTS") {
                    Toggle("Show images generated by agents", isOn: $preferences.showArtifactPreviews)
                    Picker("Presentation", selection: $preferences.artifactPresentation) {
                        ForEach(RelayArtifactPresentation.allCases) { presentation in
                            Text(presentation.label).tag(presentation)
                        }
                    }
                    .pickerStyle(.segmented)
                    .disabled(!preferences.showArtifactPreviews)
                    Text("Relay securely fetches image files referenced by Codex and Claude from the connected node.")
                        .font(.system(size: 10.5))
                        .foregroundStyle(RelayTheme.textMuted)
                        .fixedSize(horizontal: false, vertical: true)
                }
            }
            .padding(26)
        }
        .foregroundStyle(RelayTheme.text)
        .background(RelayTheme.sidebar)
    }

    private var preview: some View {
        VStack(alignment: .leading, spacing: 16) {
            Text("LIVE PREVIEW")
                .font(.system(size: 9, weight: .bold, design: .monospaced))
                .tracking(1.2)
                .foregroundStyle(RelayTheme.textFaint)
            VStack(spacing: 0) {
                HStack(spacing: 7) {
                    Circle().fill(RelayTheme.mint).frame(width: 6, height: 6)
                    Text("hpc-login  /  codex")
                        .font(.system(size: 10.5, weight: .semibold, design: .monospaced))
                    Spacer()
                    Text("CONNECTED")
                        .font(.system(size: 8, weight: .bold, design: .monospaced))
                        .foregroundStyle(RelayTheme.mint)
                }
                .padding(.horizontal, 12)
                .frame(height: 34)
                .background(RelayTheme.surface)

                VStack(alignment: .leading, spacing: 8) {
                    Text("$ codex")
                    Text("› build the next experiment")
                        .foregroundStyle(RelayTheme.textMuted)
                    Text("● Working on hpc-login")
                        .foregroundStyle(RelayTheme.mint)
                    Text("_")
                        .foregroundStyle(RelayTheme.blue)
                }
                .font(.custom(preferences.fontFamily.isEmpty ? "Menlo" : preferences.fontFamily, size: preferences.fontSize))
                .padding(preferences.terminalPadding)
                .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
                .background(Color(hex: UInt32(preferences.palette.background, radix: 16) ?? 0x0B1018))
            }
            .clipShape(RoundedRectangle(cornerRadius: 10))
            .overlay { RoundedRectangle(cornerRadius: 10).stroke(RelayTheme.line) }
        }
        .padding(26)
    }

    private func settingSection<Content: View>(_ title: String, @ViewBuilder content: () -> Content) -> some View {
        VStack(alignment: .leading, spacing: 11) {
            Text(title)
                .font(.system(size: 9, weight: .bold, design: .monospaced))
                .tracking(1.1)
                .foregroundStyle(RelayTheme.textFaint)
            content()
        }
    }

    private func valueSlider(_ label: String, value: Binding<Double>, range: ClosedRange<Double>, suffix: String) -> some View {
        HStack(spacing: 10) {
            Text(label).font(.system(size: 11.5)).frame(width: 48, alignment: .leading)
            Slider(value: value, in: range, step: 0.5).tint(RelayTheme.blue)
            Text("\(value.wrappedValue, specifier: "%.1f") \(suffix)")
                .font(.system(size: 10, weight: .medium, design: .monospaced))
                .foregroundStyle(RelayTheme.textMuted)
                .frame(width: 57, alignment: .trailing)
        }
    }
}
