import SwiftUI

struct RelaySettingsView: View {
    @ObservedObject private var preferences = RelayPreferences.shared
    @State private var showingKeyBindings = false
    @State private var terminfoStatus = RelayTerminfo.status

    var body: some View {
        HStack(spacing: 0) {
            settings
                .frame(width: 350)
            Divider().overlay(RelayTheme.line.opacity(0.45))
            preview
                .frame(maxWidth: .infinity, maxHeight: .infinity)
        }
        .frame(width: 760, height: 500)
        .background(RelayTheme.canvas)
        .preferredColorScheme(.dark)
        .sheet(isPresented: $showingKeyBindings) {
            RelayKeyBindingsView()
        }
    }

    private var settings: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 22) {
                VStack(alignment: .leading, spacing: 5) {
                    Text("Settings")
                        .font(.system(size: 19, weight: .semibold))
                    Text("Terminal and workspace preferences")
                        .font(.system(size: 12))
                        .foregroundStyle(RelayTheme.textMuted)
                }

                settingSection("Terminal") {
                    TextField("Font family", text: $preferences.fontFamily)
                        .textFieldStyle(.plain)
                        .padding(.horizontal, 10)
                        .frame(height: 32)
                        .background(RelayTheme.elevated, in: RoundedRectangle(cornerRadius: 8, style: .continuous))
                    if preferences.isUsingFontFallback {
                        Text("Font not installed — using Menlo")
                            .font(.system(size: 10.5))
                            .foregroundStyle(RelayTheme.coral)
                    }
                    valueSlider("Size", value: $preferences.fontSize, range: 9...24, suffix: "pt")
                    valueSlider("Padding", value: $preferences.terminalPadding, range: 0...20, suffix: "px")
                    Toggle("Blink cursor", isOn: $preferences.cursorBlink)
                }

                settingSection("Workspace") {
                    Picker("Palette", selection: $preferences.palette) {
                        ForEach(RelayTerminalPalette.allCases) { palette in
                            Text(palette.label).tag(palette)
                        }
                    }
                    .pickerStyle(.segmented)
                    Toggle("Compact interface", isOn: $preferences.compactInterface)
                    Toggle("Hide navigator in full screen", isOn: $preferences.hideSidebarInFullScreen)
                }

                settingSection("Keyboard") {
                    Button {
                        showingKeyBindings = true
                    } label: {
                        HStack(spacing: 9) {
                            Image(systemName: "keyboard")
                                .foregroundStyle(RelayTheme.blue)
                            Text("Customize shortcuts")
                                .font(.system(size: 11.5, weight: .medium))
                            Spacer()
                            Text(preferences.keyBinding(for: .closePane).displayName)
                                .font(.system(size: 10.5, weight: .medium, design: .monospaced))
                                .foregroundStyle(RelayTheme.textMuted)
                            Image(systemName: "chevron.right")
                                .font(.system(size: 9, weight: .semibold))
                                .foregroundStyle(RelayTheme.textMuted)
                        }
                        .contentShape(Rectangle())
                    }
                    .buttonStyle(.plain)
                    Text("Shortcuts are checked for conflicts and update menus immediately.")
                        .font(.system(size: 10.5))
                        .foregroundStyle(RelayTheme.textMuted)
                }

                settingSection("Images") {
                    Toggle("Show images generated by agents", isOn: $preferences.showArtifactPreviews)
                    Picker("Presentation", selection: $preferences.artifactPresentation) {
                        ForEach(RelayArtifactPresentation.allCases) { presentation in
                            Text(presentation.label).tag(presentation)
                        }
                    }
                    .pickerStyle(.segmented)
                    .disabled(!preferences.showArtifactPreviews)
                    Text("Relay securely fetches image files referenced by Codex and Claude from the connected node.")
                        .font(.system(size: 10.5))
                        .foregroundStyle(RelayTheme.textMuted)
                        .fixedSize(horizontal: false, vertical: true)
                }

                settingSection("Remote sessions") {
                    Toggle("Update relayd on approved hosts", isOn: $preferences.automaticallyUpdateRelayd)
                    Button {
                        NotificationCenter.default.post(name: .relayManageRelayd, object: nil)
                    } label: {
                        HStack(spacing: 9) {
                            Image(systemName: "server.rack")
                                .foregroundStyle(RelayTheme.mint)
                            Text("Check relayd and remote sessions")
                                .font(.system(size: 11.5, weight: .medium))
                            Spacer()
                            Image(systemName: "chevron.right")
                                .font(.system(size: 9, weight: .semibold))
                                .foregroundStyle(RelayTheme.textMuted)
                        }
                        .contentShape(Rectangle())
                    }
                    .buttonStyle(.plain)
                    Text("Relay asks before the first installation in a shared home. Nodes reuse that binary while keeping separate supervisors and sockets. Approved SSH hosts can apply verified updates automatically.")
                        .font(.system(size: 10.5))
                        .foregroundStyle(RelayTheme.textMuted)
                        .fixedSize(horizontal: false, vertical: true)
                }

                settingSection("Terminal compatibility") {
                    HStack(spacing: 9) {
                        Image(systemName: terminfoStatus.usesRelayEntry
                            ? "checkmark.circle.fill" : "exclamationmark.triangle.fill")
                            .foregroundStyle(terminfoStatus.usesRelayEntry
                                ? RelayTheme.mint : RelayTheme.coral)
                        VStack(alignment: .leading, spacing: 2) {
                            Text(terminfoStatus.activeTerm)
                                .font(.system(size: 11.5, weight: .semibold, design: .monospaced))
                            Text("SHA-256  \(String(terminfoStatus.hash.prefix(12)))")
                                .font(.system(size: 9.5, design: .monospaced))
                                .foregroundStyle(RelayTheme.textMuted)
                        }
                        Spacer()
                        Button("Recheck") { terminfoStatus = RelayTerminfo.bootstrap() }
                            .font(.system(size: 10.5, weight: .medium))
                    }
                    Text(terminfoStatus.message)
                        .font(.system(size: 10.5))
                        .foregroundStyle(RelayTheme.textMuted)
                        .fixedSize(horizontal: false, vertical: true)
                    if !terminfoStatus.installedForSystemPrograms {
                        HStack(spacing: 10) {
                            Button("Copy sudo fallback") {
                                copyToPasteboard(RelayTerminfo.sudoCompatibilityCommand)
                            }
                            if let command = RelayTerminfo.privilegedInstallCommand {
                                Button("Copy one-time install") {
                                    copyToPasteboard(command)
                                }
                            }
                        }
                        .font(.system(size: 10.5, weight: .medium))
                        Text("Relay never requests administrator access automatically. The fallback keeps sudo programs usable; the optional install makes xterm-relay visible to root.")
                            .font(.system(size: 10))
                            .foregroundStyle(RelayTheme.textMuted)
                            .fixedSize(horizontal: false, vertical: true)
                    }
                }

                settingSection("Agent intelligence") {
                    Toggle("On-device model refinement (experimental)", isOn: $preferences.intelligenceEnabled)
                    Toggle("Summarize completed work", isOn: $preferences.automaticAgentSummaries)
                        .disabled(!preferences.intelligenceEnabled)
                    Toggle("Semantic activity search", isOn: $preferences.semanticAgentSearch)
                        .disabled(!preferences.intelligenceEnabled)
                    Text("Off by default. Exact agent activity, subagents, peer events, and lexical search work without it. Enabling this starts local Apple Foundation Models only for summaries and ranking; it never inspects keystrokes or generates terminal completions.")
                        .font(.system(size: 10.5))
                        .foregroundStyle(RelayTheme.textMuted)
                        .fixedSize(horizontal: false, vertical: true)
                }
            }
            .padding(26)
        }
        .foregroundStyle(RelayTheme.text)
        .background(RelayTheme.sidebar)
        .onAppear { terminfoStatus = RelayTerminfo.status }
    }

    private var preview: some View {
        VStack(alignment: .leading, spacing: 16) {
            Text("Preview")
                .font(.system(size: 12, weight: .medium))
                .foregroundStyle(RelayTheme.textMuted)
            VStack(spacing: 0) {
                HStack(spacing: 7) {
                    Circle().fill(RelayTheme.mint).frame(width: 6, height: 6)
                    Text("hpc-login  /  codex")
                        .font(.system(size: 10.5, weight: .medium))
                    Spacer()
                    Text("Connected")
                        .font(.system(size: 9, weight: .medium))
                        .foregroundStyle(RelayTheme.mint)
                }
                .padding(.horizontal, 12)
                .frame(height: 34)
                .background(RelayTheme.surface)

                VStack(alignment: .leading, spacing: 8) {
                    Text("$ codex")
                    Text("› build the next experiment")
                        .foregroundStyle(RelayTheme.textMuted)
                    Text("● Working on hpc-login")
                        .foregroundStyle(RelayTheme.mint)
                    Text("_")
                        .foregroundStyle(RelayTheme.blue)
                }
                .font(.custom(preferences.resolvedFontFamily, size: preferences.fontSize))
                .padding(preferences.terminalPadding)
                .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
                .background(Color(hex: UInt32(preferences.palette.background, radix: 16) ?? 0x0B1018))
            }
            .clipShape(RoundedRectangle(cornerRadius: 12, style: .continuous))
            .overlay { RoundedRectangle(cornerRadius: 12).stroke(RelayTheme.line.opacity(0.55)) }
        }
        .padding(26)
    }

    private func settingSection<Content: View>(_ title: String, @ViewBuilder content: () -> Content) -> some View {
        VStack(alignment: .leading, spacing: 9) {
            Text(title)
                .font(.system(size: 12, weight: .medium))
                .foregroundStyle(RelayTheme.textMuted)
            VStack(alignment: .leading, spacing: 12) {
                content()
            }
            .padding(12)
            .background(RelayTheme.surface, in: RoundedRectangle(cornerRadius: 12, style: .continuous))
        }
    }

    private func valueSlider(_ label: String, value: Binding<Double>, range: ClosedRange<Double>, suffix: String) -> some View {
        HStack(spacing: 10) {
            Text(label).font(.system(size: 11.5)).frame(width: 48, alignment: .leading)
            Slider(value: value, in: range, step: 0.5).tint(RelayTheme.blue)
            Text("\(value.wrappedValue, specifier: "%.1f") \(suffix)")
                .font(.system(size: 10, weight: .medium, design: .monospaced))
                .foregroundStyle(RelayTheme.textMuted)
                .frame(width: 57, alignment: .trailing)
        }
    }

    private func copyToPasteboard(_ value: String) {
        NSPasteboard.general.clearContents()
        NSPasteboard.general.setString(value, forType: .string)
    }
}

private struct RelayKeyBindingsView: View {
    @ObservedObject private var preferences = RelayPreferences.shared
    @Environment(\.dismiss) private var dismiss
    @State private var conflictMessage: String?

    private let sections = ["Sessions", "Tabs", "Panes", "Workspace"]

    var body: some View {
        VStack(spacing: 0) {
            HStack(spacing: 12) {
                VStack(alignment: .leading, spacing: 3) {
                    Text("Keybindings")
                        .font(.system(size: 18, weight: .semibold))
                    Text("Click a shortcut, then press a new key combination.")
                        .font(.system(size: 11.5))
                        .foregroundStyle(RelayTheme.textMuted)
                }
                Spacer()
                Button("Reset all") {
                    preferences.resetAllKeyBindings()
                    conflictMessage = nil
                }
                Button("Done") { dismiss() }
                    .keyboardShortcut(.defaultAction)
            }
            .padding(.horizontal, 22)
            .frame(height: 70)

            Divider().overlay(RelayTheme.line.opacity(0.5))

            ScrollView {
                LazyVStack(alignment: .leading, spacing: 18) {
                    if let conflictMessage {
                        Label(conflictMessage, systemImage: "exclamationmark.triangle.fill")
                            .font(.system(size: 11))
                            .foregroundStyle(RelayTheme.coral)
                            .padding(.horizontal, 12)
                            .frame(maxWidth: .infinity, minHeight: 34, alignment: .leading)
                            .background(RelayTheme.coral.opacity(0.09), in: RoundedRectangle(cornerRadius: 9))
                    }

                    ForEach(sections, id: \.self) { section in
                        VStack(alignment: .leading, spacing: 7) {
                            Text(section)
                                .font(.system(size: 10.5, weight: .semibold))
                                .foregroundStyle(RelayTheme.textMuted)
                                .textCase(.uppercase)
                                .tracking(0.5)

                            VStack(spacing: 0) {
                                let commands = RelayCommand.allCases.filter { $0.section == section }
                                ForEach(Array(commands.enumerated()), id: \.element.id) { index, command in
                                    keyBindingRow(command)
                                    if index < commands.count - 1 {
                                        Divider().overlay(RelayTheme.line.opacity(0.35))
                                    }
                                }
                            }
                            .background(RelayTheme.surface, in: RoundedRectangle(cornerRadius: 11, style: .continuous))
                            .overlay {
                                RoundedRectangle(cornerRadius: 11, style: .continuous)
                                    .stroke(RelayTheme.line.opacity(0.45))
                            }
                        }
                    }
                }
                .padding(22)
            }
        }
        .frame(width: 590, height: 560)
        .foregroundStyle(RelayTheme.text)
        .background(RelayTheme.sidebar)
        .preferredColorScheme(.dark)
    }

    private func keyBindingRow(_ command: RelayCommand) -> some View {
        HStack(spacing: 12) {
            Text(command.label)
                .font(.system(size: 11.5))
            Spacer()
            if preferences.keyBindings[command.rawValue] != nil {
                Button {
                    preferences.resetKeyBinding(command)
                    conflictMessage = nil
                } label: {
                    Image(systemName: "arrow.counterclockwise")
                        .font(.system(size: 10, weight: .medium))
                        .foregroundStyle(RelayTheme.textMuted)
                }
                .buttonStyle(.plain)
                .help("Restore default")
            }
            RelayShortcutRecorderButton(binding: preferences.keyBinding(for: command)) { candidate in
                if let conflict = preferences.setKeyBinding(candidate, for: command) {
                    conflictMessage = "\(candidate.displayName) is already assigned to \(conflict.label)."
                    NSSound.beep()
                } else {
                    conflictMessage = nil
                }
            }
        }
        .padding(.horizontal, 12)
        .frame(height: 40)
    }
}

private struct RelayShortcutRecorderButton: View {
    let binding: RelayKeyBinding
    let onCapture: (RelayKeyBinding) -> Void
    @State private var isRecording = false
    @State private var monitor: Any?

    var body: some View {
        Button {
            beginRecording()
        } label: {
            Text(isRecording ? "Type shortcut…" : binding.displayName)
                .font(.system(size: 10.5, weight: .semibold, design: .monospaced))
                .foregroundStyle(isRecording ? RelayTheme.canvas : RelayTheme.text)
                .frame(minWidth: 74)
                .padding(.horizontal, 8)
                .frame(height: 25)
                .background(
                    isRecording ? RelayTheme.blue : RelayTheme.elevated,
                    in: RoundedRectangle(cornerRadius: 6, style: .continuous)
                )
                .overlay {
                    RoundedRectangle(cornerRadius: 6, style: .continuous)
                        .stroke(isRecording ? RelayTheme.blue : RelayTheme.line.opacity(0.6))
                }
        }
        .buttonStyle(.plain)
        .accessibilityLabel("Shortcut: \(binding.displayName)")
        .onDisappear { stopRecording() }
    }

    private func beginRecording() {
        guard !isRecording else { return }
        isRecording = true
        monitor = NSEvent.addLocalMonitorForEvents(matching: .keyDown) { event in
            if event.keyCode == 53 {
                stopRecording()
                return nil
            }
            guard let candidate = RelayKeyBinding(event: event) else {
                NSSound.beep()
                return nil
            }
            onCapture(candidate)
            stopRecording()
            return nil
        }
    }

    private func stopRecording() {
        if let monitor { NSEvent.removeMonitor(monitor) }
        monitor = nil
        isRecording = false
    }
}
